export const urlCategoryMap = new Map([
    ['/na/en-us', ''],
    ['/na/en-us/be-whats-next/360value', ''],
    ['/na/en-us/be-whats-next/better-nutrition-key-to-added-value-consumers-seek', ''],
    ['/na/en-us/be-whats-next/food-beverage-industry-health-trends', ''],
    ['/na/en-us/be-whats-next/growth-with-clean-label', ''],
    ['/na/en-us/be-whats-next/making-whats-next-possible', ''],
    ['/na/en-us/be-whats-next/psychology-clean-label', ''],
    ['/na/en-us/be-whats-next/succeeding-with-plant-protein-ingredients', ''],
    ['/na/en-us/be-whats-next/whats-next-for-the-food-industry', ''],
    ['/na/en-us/be-whats-next/whats-next-in-culinology', ''],
    ['/na/en-us/be-whats-next/whats-next-in-sugar-reduction', ''],
    ['/na/en-us/categories/animal-nutrition', ''],
    ['/na/en-us/categories/beauty-home', ''],
    ['/na/en-us/categories/beauty-home/hair-care', 'Hair Care / Salon Hair Care, Hair Care'],
    ['/na/en-us/categories/beauty-home/hair-care/hair-styling', 'Hair Care / Salon Hair Care, Hair Care Hair Care / Styling agent'],
    ['/na/en-us/categories/beauty-home/skin-care', 'Mens Grooming / Mens Toiletries / Skin Care, Skin Care / Other Skin care, Skin Care'],
    ['/na/en-us/categories/beauty-home/sun-care', ''],
    ['/na/en-us/categories/beverages', ''],
    ['/na/en-us/categories/beverages/coffee-and-tea', 'Non-alcoholic beverage / Coffee beverage, Non-alcoholic beverage / Tea beverage'],
    ['/na/en-us/categories/beverages/dairy-alternative-dairy-beverages', 'Non-alcoholic beverage / Other beverages'],
    ['/na/en-us/categories/beverages/nutrition-beverages', 'Non-alcoholic beverage / Powder drink mix'],
    ['/na/en-us/categories/food', ''],
    ['/na/en-us/categories/food/bakery', 'Bakery'],
    ['/na/en-us/categories/food/batters-breadings', ''],
    ['/na/en-us/categories/food/dairy/cheese', ''],
    ['/na/en-us/categories/food/dairy/yogurt-and-cultured-products', ''],
    ['/na/en-us/categories/food/plant-based-meat', ''],
    ['/na/en-us/categories/food/savory', 'Savory'],
    ['/na/en-us/categories/food/savory/dressings-dips', 'Savory / Sauces & dressing'],
    ['/na/en-us/categories/food/savory/ready-meals', 'Savory / Ready meal, meal component'],
    ['/na/en-us/categories/food/savory/soups-sauces-gravies', 'Savory / Soup, Savory / Sauces & dressing'],
    ['/na/en-us/categories/paper-corrugating', ''],
    ['/na/en-us/company/expertise', ''],
    ['/na/en-us/company/expertise/food-service/sugar-reduction', ''],
    ['/na/en-us/company/expertise/plant-based-proteins', ''],
    ['/na/en-us/company/expertise/texturants', ''],
    ['/na/en-us/company/expertise/texturants/lets-talk-texture', ''],
    ['/na/en-us/ingredients/ingredient-product-families/astraea-allulose', ''],
    ['/na/en-us/ingredients/ingredient-product-families/fibertex-multi-benefit-fibers', ''],
    ['/na/en-us/ingredients/ingredient-product-families/homecraft-create-multi-functional-tapioca-flours', ''],
    ['/na/en-us/ingredients/ingredient-product-families/novation-functional-native-starches', ''],
    ['/na/en-us/ingredients/ingredient-product-families/novation-indulge-starches', ''],
    ['/na/en-us/ingredients/ingredient-product-families/novation-lumina-functional-native-starches', ''],
    ['/na/en-us/ingredients/ingredient-product-families/precisa', 'Snack'],
    ['/na/en-us/ingredients/ingredient-product-families/purecircle-by-ingredion-stevia-solutions', ''],
    ['/na/en-us/ingredients/ingredient-product-families/purity-p-pea-starch', ''],
    ['/na/en-us/ingredients/ingredient-product-families/versasweet-low-sugar-glucose-syrups', ''],
    ['/na/en-us/ingredients/ingredient-product-families/vitessence-plant-protein-isolates', ''],
    ['/na/en-us/ingredients/ingredient-product-families/vitessence-plant-protein-isolates/protein-isolates-for-plant-based-dairy', ''],
    ['/na/en-us/ingredients/ingredient-types/allulose', ''],
    ['/na/en-us/ingredients/ingredient-types/flours', ''],
    ['/na/en-us/ingredients/ingredient-types/gums-hydrocolloids', ''],
    ['/na/en-us/ingredients/ingredient-types/rice-starches-and-flours', ''],
    ['/na/en-us/ingredients/ingredient-types/starches', ''],
    ['/na/en-us/ingredients/ingredient-types/starches/potato-starch', ''],
    ['/na/en-us/ingredients/ingredient-types/stevia', ''],
    ['/na/en-us/ingredients/ingredient-types/sweeteners', ''],
    ['/na/en-us/news-events/events/algorithm-for-success-healthy-crispy-and-delicious', ''],
    ['/na/en-us/news-events/events/bevnet-live-2022', ''],
    ['/na/en-us/news-events/events/Bridge2Food_Plant-Based_Foods_and_Proteins_Summit_Americas', ''],
    ['/na/en-us/news-events/events/California_Supplier_Day', ''],
    ['/na/en-us/news-events/events/Cheese_Expo_2022_Global_Technology_for_Dairy_Processors', ''],
    ['/na/en-us/news-events/events/Clean_Label_Conference_2022', ''],
    ['/na/en-us/news-events/events/FIRST-2021-IFT-digital-experience', ''],
    ['/na/en-us/news-events/events/ibie-2022', 'Bakery'],
    ['/na/en-us/news-events/events/IFT_', ''],
    ['/na/en-us/news-events/events/IFT-FIRST-2023', ''],
    ['/na/en-us/news-events/events/ift-first-2024', ''],
    ['/na/en-us/news-events/events/in-cosmetics-global-2023', ''],
    ['/na/en-us/news-events/events/maximize-brand-value-by-meeting-evolving-consumer-needs', ''],
    ['/na/en-us/news-events/events/Natural_Products_Expo_West_2022', ''],
    ['/na/en-us/news-events/events/Natural_Products_Expo_West_2023', ''],
    ['/na/en-us/news-events/events/New_York_Suppliers_Day', ''],
    ['/na/en-us/news-events/events/NYSCC_Suppliers_Day_2022', ''],
    ['/na/en-us/news-events/events/NYSCC_Suppliers_Day_2023', 'Bath & Shower, Color Cosmetics, Hair Care, Men\'s Grooming, Oral Care, Skin Care, Baby product, Deodorant, Fragrance, Other Personal Care'],
    ['/na/en-us/news-events/events/Petfood_Forum_2022', ''],
    ['/na/en-us/news-events/events/solving-texture-equation', ''],
    ['/na/en-us/news-events/events/ssw-2022', ''],
    ['/na/en-us/news-events/events/supplyside-west-2023', ''],
    ['/na/en-us/news-events/events/supplyside-west-2024', ''],
    ['/na/en-us/news-events/events/The_Sweets_and_Snacks_Expo_by_National_Confectioners_Association', ''],
    ['/na/en-us/news-events/news/breakthrough-ingredion-stevia-solution-unmatched-in-consumer-testing', ''],
    ['/na/en-us/news-events/news/EVANESSE', ''],
    ['/na/en-us/news-events/news/fda-draft-guidance-on-allulose-unlocks-opportunity-for-food-and-', ''],
    ['/na/en-us/news-events/news/Idea-Labs-global-texture-and-taste-trends', ''],
    ['/na/en-us/news-events/news/Ingredion_Announces_InnovoPro_Equity_Investment', ''],
    ['/na/en-us/news-events/news/ingredion-and-innovopro-sign-exclusive-commercial-distribution-partnership', ''],
    ['/na/en-us/news-events/news/ingredion-brings-clean-label-texturizers-made-from-citrus-peels-to-the-us', ''],
    ['/na/en-us/news-events/news/ingredion-completes-rice-manufacturing-expansion', ''],
    ['/na/en-us/news-events/news/ingredion-launches-first-functional-native-clean-label-starch', ''],
    ['/na/en-us/news-events/news/ingredion-makes-progress-toward-capacity-expansion', ''],
    ['/na/en-us/news-events/news/ingredion-wins-2022-world-plant-based-award', ''],
    ['/na/en-us/news-events/news/Kerr-by-Ingredion-names-marketing-manager', ''],
    ['/na/en-us/news-events/news/lca-stevia-innovation-accelerates-sustainability', ''],
    ['/na/en-us/news-events/news/multi-benefit-naturally-sourced-clean-label-citrus-fiber', ''],
    ['/na/en-us/news-events/news/new-pea-protein-launched-to-maintain-softness-throughout-shelf-l', 'Snack / Nutrition bar & ball'],
    ['/na/en-us/news-events/news/Organic', ''],
    ['/na/en-us/news-events/news/Pea-protein-improved-dispersibility-RTM-beverages', ''],
    ['/na/en-us/news-events/news/purecircle-awarded-plant-breeders-rights-for-breakthrough-stevia-varietal', ''],
    ['/na/en-us/news-events/news/uk-food-safety-authority-approves-reb-m-bioconversion', ''],
    ['/na/en-us/news-events/news/ultratex-1311', ''],
    ['/na/en-us/news-events/news/VITESSENCE-Pulse-1803', ''],
    ['/na/en-us/news-events/news/VITESSENCE-TEX-Crumbles-102', ''],
    ['/na/en-us/redirect/REDIRECT-FIF-webinar', ''],
    ['/na/en-us/solving-a-challenge/challenges/eating-drinking-experience', ''],
    ['/na/en-us/solving-a-challenge/challenges/gluten-free', 'Bakery / Bread, bread mix / Gluten free bread, Bakery / Biscuit, cookie, cracker / Gluten free biscuit, cracker, cookie'],
    ['/na/en-us/solving-a-challenge/challenges/non-gmo', ''],
    ['/na/en-us/solving-a-challenge/challenges/nutrition-minus', ''],
    ['/na/en-us/solving-a-challenge/challenges/sugar-reduction-specialty-sweeteners', 'Other food / Tabletop sweetener, Non-alcoholic beverage / Table top sweetener'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community', 'Snack, Snack / Other Snack'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/consumer-challenges', 'Snack, Snack / Other Snack'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-innovation-news', 'Snack / Other Snack, Snack'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-inspiration/beet-crackers', 'Bakery, Snack, Bakery / Biscuit, cookie, cracker / Cracker, pretzel, Bakery / Biscuit, cookie, cracker'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-inspiration/falafe-spiced-quinoa-chip', 'Snack, Snack / Chip, Snack / Chip / Baked chip'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-inspiration/massaman-curried-nuts', 'Snack, Snack / Coated nut'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-inspiration/vegan-macarons', 'Bakery, Snack, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Biscuit, Bakery / Biscuit, cookie, cracker / Cookie, Bakery / Biscuit, cookie, cracker / Gluten free biscuit, cracker, cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-inspiration/vegan-meringues', 'Bakery, Snack, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Biscuit, Bakery / Biscuit, cookie, cracker / Cookie, Bakery / Biscuit, cookie, cracker / Gluten free biscuit, cracker, cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/biscuit-with-no-added-sugar-lemon-filling', 'Bakery, Bakery / Bakery filling, topping, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Biscuit, Bakery / Bakery filling, topping / Fat based filling'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/crispy-and-flaky-cream-cracker', 'Bakery / Biscuit, cookie, cracker / Cracker, pretzel Bakery, Bakery / Biscuit, cookie, cracker'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/faqs-crackers', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cracker, pretzel'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/faqs-soft-cookies', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/high-protein-bar', 'Snack, Snack / Nutrition bar & ball'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/high-protein-cookies', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/high-protein-crackers', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cracker, pretzel'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/light-and-crispy-wheat-cracker', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cracker, pretzel'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/muesli-cranberries-cookie', 'Bakery / Biscuit, cookie, cracker / Cookie Bakery, Bakery / Biscuit, cookie, cracker'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/protein-bar-demo', 'Snack, Snack / Nutrition bar & ball'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/puff-snack-cracker', 'Bakery / Biscuit, cookie, cracker / Cracker, pretzel, Snack / Other Snack / Regional snack Bakery, Snack, Bakery / Biscuit, cookie, cracker'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-knowledge/thin-and-crisp-baked-potato-snack', 'Snack / Chip / Baked chip Snack, Snack / Chip'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-manufacturer-challenges', 'Snack, Snack / Other Snack'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-troubleshooting/chocolate-protein-cookies', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-troubleshooting/cookies-spread-too-much', 'Bakery / Biscuit, cookie, cracker, Bakery, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-troubleshooting/dry-cookies', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-troubleshooting/greasy-cookies', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/innovation-with-idea-labs/snacking-innovation-community/snacking-troubleshooting/grittiness-gluten-free-cookies', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Gluten free biscuit, cracker, cookie'],
    ['/na/en-us/solving-a-challenge/resource-library/2022-holiday-greeting', ''],
    ['/na/en-us/solving-a-challenge/resource-library/60-percent-reduced-sugar-chewy-granola-bar', 'Snack'],
    ['/na/en-us/solving-a-challenge/resource-library/6-percent-protein-plant-based-pea-milk', 'Non-alcoholic beverage / Other beverages, Non-alcoholic beverage Dairy Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/95-percent-reduced-sguar-high-protein-bar', 'Snack'],
    ['/na/en-us/solving-a-challenge/resource-library/acacia-max-whitepaper', 'Beverage emulsion & powder / Beverage emulsion'],
    ['/na/en-us/solving-a-challenge/resource-library/accelerating-plant-based-market', 'Snack, Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/acidified-beverages', 'Dairy / Dairy beverages / Acidified and fermented milk drink'],
    ['/na/en-us/solving-a-challenge/resource-library/adhesive-strategies-whitepaper', 'Adhesive & sealant, Corrugated'],
    ['/na/en-us/solving-a-challenge/resource-library/algorithm-for-success-healthy-crispy-delicious', 'Snack'],
    ['/na/en-us/solving-a-challenge/resource-library/allulose-infographic', ''],
    ['/na/en-us/solving-a-challenge/resource-library/american-style-slice-cheese', 'Dairy alternative (Dairy free) / Cheese alternative, Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/apple-pectin-whitepaper', ''],
    ['/na/en-us/solving-a-challenge/resource-library/baking-your-holidays-better-and-brighter', 'Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/resource-library/berry-flavored-water', 'Non-alcoholic beverage / Water / Flavored Water Non-alcoholic beverage / Water, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/binding-syrups-bars', 'Bakery, Snack, Snack / Nutrition bar & ball'],
    ['/na/en-us/solving-a-challenge/resource-library/blackberry-sports-recovery-beverage', 'Non-alcoholic beverage / Other beverages, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/black-sesame-cashew-beverage', 'Dairy alternative (Dairy free) / Milk beverage Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/buttered-coffee', 'Non-alcoholic beverage / Coffee beverage Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/carbonated-orange-pineapple-energy-drink', 'Non-alcoholic beverage / Energy Drink, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/cashew-yogurt', 'Dairy alternative (Dairy free) / Yogurt alternative, Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/cherry-beet-juice', 'Non-alcoholic beverage / Juice, nectar, juice drink Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/chicken-nugget-coatings', ''],
    ['/na/en-us/solving-a-challenge/resource-library/chocolate-instant-plant-protein-beverage', 'Non-alcoholic beverage / Powder drink mix, Dairy alternative (Dairy free) / Milk beverage, Dairy alternative (Dairy free), Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/chocolate-milk-mix', 'Dairy / Dairy beverages / Flavored milk, Non-alcoholic beverage / Powder drink mix, Non-alcoholic beverage, Dairy, Dairy / Dairy beverages'],
    ['/na/en-us/solving-a-challenge/resource-library/chocolate-protein-beverage', 'Dairy / Other Dairy'],
    ['/na/en-us/solving-a-challenge/resource-library/chocolate-RTD-protein-beverage', 'Non-alcoholic beverage / Other beverages, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/citrus-squeeze-carbonated-beverage', 'Beverage emulsion & powder / Beverage emulsion, Non-alcoholic beverage / Carbonated soft drink, Non-alcoholic beverage, Beverage emulsion & powder'],
    ['/na/en-us/solving-a-challenge/resource-library/clean-label-for-babies-and-toddlers', 'Baby food toddler'],
    ['/na/en-us/solving-a-challenge/resource-library/coconut-almond-milk', 'Dairy alternative (Dairy free) / Milk beverage Dairy alternative (Dairy free), Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/coconut-chai-frozen-dessert', 'Dairy / Ice Cream, Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/cold-processed-chocolate-milk', 'Dairy / Dairy beverages / Flavored milk, Dairy, Dairy / Dairy beverages'],
    ['/na/en-us/solving-a-challenge/resource-library/common-gums-chart', 'Confectionery / Gum, mint'],
    ['/na/en-us/solving-a-challenge/resource-library/cream-sauce-cost-savings', 'Savory / Sauces & dressing / Cream based sauce Savory, Savory / Sauces & dressing'],
    ['/na/en-us/solving-a-challenge/resource-library/Curry-greek-yogurt-dip', 'Dairy / Yogurt Savory / Sauces & dressing, Savory / Sauces & dressing / Dip (refrigerated, frozen)'],
    ['/na/en-us/solving-a-challenge/resource-library/dairy-based-coffee-creamer', 'Dairy / Other Dairy, Non-alcoholic beverage / Coffee beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/dairyblend-ic21-ice-cream', 'Dairy / Other Dairy, Dairy / Ice Cream Dairy alternative (Dairy free) / Frozen dessert'],
    ['/na/en-us/solving-a-challenge/resource-library/ebook-master-the-texture-equation', ''],
    ['/na/en-us/solving-a-challenge/resource-library/ebook-the-power-of-the-label', ''],
    ['/na/en-us/solving-a-challenge/resource-library/extruded-puff', 'Snack'],
    ['/na/en-us/solving-a-challenge/resource-library/flavored-ice-cream', 'Dairy / Other Dairy'],
    ['/na/en-us/solving-a-challenge/resource-library/formulating-gelatin-free-gummies', 'Confectionery'],
    ['/na/en-us/solving-a-challenge/resource-library/formulating-made-simple', ''],
    ['/na/en-us/solving-a-challenge/resource-library/Formulation-greek-style-cashew-yogurt-alternative', 'Dairy / Yogurt / Greek Strained, Dairy alternative (Dairy free) / Yogurt alternative, Dairy alternative (Dairy free), Dairy'],
    ['/na/en-us/solving-a-challenge/resource-library/Formulation-High-Protein-Plant-Based-Vanilla-Nutrition-Beverage', 'Non-alcoholic beverage / Other beverages, Non-alcoholic beverage Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/Formulation-keto-friendly-creamy-dijon-dressing', 'Savory / Sauces & dressing'],
    ['/na/en-us/solving-a-challenge/resource-library/Formulation-keto-friendly-korean-bbq-sauce', 'Savory / Sauces & dressing Savory / Sauces & dressing / Other sauces & dressings'],
    ['/na/en-us/solving-a-challenge/resource-library/formulation-reduced-sugar-instant-beverage', 'Non-alcoholic beverage, Non-alcoholic beverage / Powder drink mix'],
    ['/na/en-us/solving-a-challenge/resource-library/Formulation-Roasted-cauliflower-hummus-dip', 'Savory / Sauces & dressing, Savory / Sauces & dressing / Dip (refrigerated, frozen)'],
    ['/na/en-us/solving-a-challenge/resource-library/french-fry-coating', 'Batter & breading / Potato product Batter & breading'],
    ['/na/en-us/solving-a-challenge/resource-library/frozen-desserts-non-dairy-based', 'Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/frozen-desserts-whitepaper', 'Dairy / Dessert / Other desserts (Including frozen)'],
    ['/na/en-us/solving-a-challenge/resource-library/full-fat-stirred-yogurt', 'Dairy / Yogurt / Stirred, Dairy, Dairy / Yogurt'],
    ['/na/en-us/solving-a-challenge/resource-library/gelatin-free-gummies', 'Confectionery'],
    ['/na/en-us/solving-a-challenge/resource-library/gluten-free-cheese-crisp', 'Bakery'],
    ['/na/en-us/solving-a-challenge/resource-library/gluten-free-high-protein-gruyere-and-black-pepper-snack-crackers', 'Snack, Bakery / Biscuit, cookie, cracker, Bakery'],
    ['/na/en-us/solving-a-challenge/resource-library/guar-flavor-free', 'Dairy, Dairy / Ice Cream'],
    ['/na/en-us/solving-a-challenge/resource-library/guide-puffs-solution', ''],
    ['/na/en-us/solving-a-challenge/resource-library/healthy-sauces-infographic', 'Savory, Savory / Sauces & dressing / Tomato based sauce, Savory / Sauces & dressing / Other sauces & dressings, Savory / Sauces & dressing / Cream based sauce, Savory / Sauces & dressing, Savory / Sauces & dressing / Marinades (i.e. soy sauces, teriyaki sauce), Savory / Sauces & dressing / Oyster sauce, Savory / Sauces & dressing / Hot sauce, Savory / Ready meal, meal component / Sauce for shelf stable ready meal'],
    ['/na/en-us/solving-a-challenge/resource-library/hibiscus-pomegranate-sparkling-beverage', 'Alcoholic Beverage / Other Alcoholic beverage, Beverage emulsion & powder / Beverage emulsion, Alcoholic Beverage, Beverage emulsion & powder'],
    ['/na/en-us/solving-a-challenge/resource-library/high-protein-rtd-beverages', 'Dairy / Dairy beverages'],
    ['/na/en-us/solving-a-challenge/resource-library/how-to-disperse-gums', ''],
    ['/na/en-us/solving-a-challenge/resource-library/how-to-reduce-sugar-in-cookies-sweet-biscuits', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/resource-library/iced-tea-mix', 'Non-alcoholic beverage / Powder drink mix, Non-alcoholic beverage / Tea beverage, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/infographic-sustainable-plant-based-proteins', ''],
    ['/na/en-us/solving-a-challenge/resource-library/instant-protein-drink', 'Non-alcoholic beverage / Powder drink mix'],
    ['/na/en-us/solving-a-challenge/resource-library/Keto-friendly-creamy-french-dressing', 'Savory / Sauces & dressing'],
    ['/na/en-us/solving-a-challenge/resource-library/lemon-lime-soft-drink', 'Non-alcoholic beverage / Carbonated soft drink, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/lemon-thyme-coconut-frozen-dessert', 'Dairy alternative (Dairy free) / Frozen dessert, Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/low-ph-rtd-beverage', 'Dairy / Dairy beverages / Acidified and fermented milk drink'],
    ['/na/en-us/solving-a-challenge/resource-library/mandarin-orange-fusion-beverage', 'Beverage emulsion & powder / Beverage emulsion, Beverage emulsion & powder'],
    ['/na/en-us/solving-a-challenge/resource-library/mango-coconut-lassi-frozen-dessert', 'Dairy alternative (Dairy free) / Frozen dessert, Dairy alternative (Dairy free)'],
    ['/na/en-us/solving-a-challenge/resource-library/marion-blackberry-iced-tea', 'Non-alcoholic beverage / Tea beverage, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/matcha-chai-tea', 'Non-alcoholic beverage / Tea beverage, Dairy alternative (Dairy free) / Milk beverage, Dairy alternative (Dairy free), Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/mocha-ready-to-drink-beverage', 'Non-alcoholic beverage / Coffee beverage, Dairy / Dairy beverages / Other milk beverage, Dairy, Dairy / Dairy beverages, Non-alcoholic beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/mono-di-replacement-ice-cream', 'Dairy, Dairy / Ice Cream'],
    ['/na/en-us/solving-a-challenge/resource-library/new-norm-sugar-labeling-podcast', ''],
    ['/na/en-us/solving-a-challenge/resource-library/next-gen-tapioca-case-study-3-in-1-coffee-mix', ''],
    ['/na/en-us/solving-a-challenge/resource-library/next-gen-tapioca-case-study-plant-based-dessert', ''],
    ['/na/en-us/solving-a-challenge/resource-library/organic-tableting0', 'Confectionery'],
    ['/na/en-us/solving-a-challenge/resource-library/organic-yogurt-whitepaper', 'Dairy, Dairy / Yogurt'],
    ['/na/en-us/solving-a-challenge/resource-library/pea-protein-isolate-antidumping', ''],
    ['/na/en-us/solving-a-challenge/resource-library/plant-based-italian-sausauge-crumbles', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/plant-based-protein-burger', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/plant-based-protein-portfolio', ''],
    ['/na/en-us/solving-a-challenge/resource-library/Plant-based-reduced-sugar-matcha-chai-instant-shake', 'Dairy / Dairy beverages'],
    ['/na/en-us/solving-a-challenge/resource-library/plant-based-seafood-patty', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/plant-based-shredded-chicken', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/plant-based-yogurt', 'Dairy alternative (Dairy free), Dairy alternative (Dairy free) / Yogurt alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/plant-proteins-healthy-snacks', 'Snack, Snack / Extruded snack'],
    ['/na/en-us/solving-a-challenge/resource-library/prickly-pear-margarita-drink', 'Alcoholic Beverage / Other Alcoholic beverage, Beverage emulsion & powder / Beverage emulsion Alcoholic Beverage, Beverage emulsion & powder'],
    ['/na/en-us/solving-a-challenge/resource-library/pudding', 'Dairy / Dessert / Spoonable dessert (pudding, custard, flan), Dairy, Dairy / Dessert'],
    ['/na/en-us/solving-a-challenge/resource-library/pulses-for-pet-food', 'Pet food'],
    ['/na/en-us/solving-a-challenge/resource-library/pulses-i2s-brief', ''],
    ['/na/en-us/solving-a-challenge/resource-library/purecircle-reb-m-suitability-assessment', ''],
    ['/na/en-us/solving-a-challenge/resource-library/Ready-to-drink-raspberry-yogurt-beverage', 'Dairy / Yogurt / Drinkable, Non-alcoholic beverage, Dairy / Dairy beverages, Dairy / Yogurt, Dairy / Dairy beverages / Acidified and fermented milk drink, Dairy'],
    ['/na/en-us/solving-a-challenge/resource-library/reduce-breakage-and-improve-the-eating-experience', 'Snack / Chip, Bakery / Biscuit, cookie, cracker'],
    ['/na/en-us/solving-a-challenge/resource-library/replacing-titanium-dioxide', ''],
    ['/na/en-us/solving-a-challenge/resource-library/rtd-beverages-whitepaper', 'Dairy alternative (Dairy free) / Milk beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/sangria-flavored-beverage', 'Beverage emulsion & powder / Beverage emulsion, Non-alcoholic beverage / Other beverages, Non-alcoholic beverage, Beverage emulsion & powder'],
    ['/na/en-us/solving-a-challenge/resource-library/Sauces-and-dressings-e-guide', 'Savory / Sauces & dressing Savory'],
    ['/na/en-us/solving-a-challenge/resource-library/simplistica-flavored-water', 'Non-alcoholic beverage / Water / Flavored Water'],
    ['/na/en-us/solving-a-challenge/resource-library/sports-nutrition-beverages-infographic', 'Non-alcoholic beverage / Sport drink'],
    ['/na/en-us/solving-a-challenge/resource-library/strawberry-flavored-yogurt-drink', 'Dairy / Yogurt / Drinkable, Dairy / Yogurt, Dairy'],
    ['/na/en-us/solving-a-challenge/resource-library/sweetener-life-cycle-assessment-e-book', ''],
    ['/na/en-us/solving-a-challenge/resource-library/tomato-solids-replacement', 'Savory / Sauces & dressing / Tomato based sauce Savory, Savory / Sauces & dressing'],
    ['/na/en-us/solving-a-challenge/resource-library/troubleshooting-extruded-snacks-expert-article', 'Snack Snack / Extruded snack'],
    ['/na/en-us/solving-a-challenge/resource-library/ultrasmooth-ngmo', 'Non-alcoholic beverage / Powder drink mix'],
    ['/na/en-us/solving-a-challenge/resource-library/vanilla-fruit-prep-for-blended-yogurt', 'Dairy / Fruit Preparation / Fruit preparation for yoghurt, ice cream, desserts, Dairy, Dairy / Fruit Preparation'],
    ['/na/en-us/solving-a-challenge/resource-library/vanilla-ice-cream', 'Dairy, Dairy / Ice Cream'],
    ['/na/en-us/solving-a-challenge/resource-library/vanilla-RTD-protein-beverage', 'Non-alcoholic beverage / Other beverages, Non-alcoholic beverage Dairy'],
    ['/na/en-us/solving-a-challenge/resource-library/vegan-cheese-whitepaper', 'Dairy alternative (Dairy free), Dairy alternative (Dairy free) / Cheese alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/vegetarian-frankfurter', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/video-acacia-emulsifier', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-alternative-universe', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-aquafaba-vegan-emulsifying-webinar', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-break-through-organic-webinar', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-clean-label-landscape-webinar', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-commercial-baking-with-allulose-apricot-fig-cookies', 'Bakery, Bakery / Biscuit, cookie, cracker, Bakery / Biscuit, cookie, cracker / Cookie'],
    ['/na/en-us/solving-a-challenge/resource-library/video-consumer-simple-label-webinar', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-deliver-on-the-plant-based-protein-demand', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-demand-clean-label-poultry', 'Meat, fish, poultry'],
    ['/na/en-us/solving-a-challenge/resource-library/video-differentiate-product-clean-label-webinar', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-formulating-beverages-allulose-shakerato-aqua-fresca', 'Non-alcoholic beverage, Non-alcoholic beverage / Coffee beverage, Non-alcoholic beverage / Water, Non-alcoholic beverage / Juice, nectar, juice drink'],
    ['/na/en-us/solving-a-challenge/resource-library/video-formulating-for-a-fast-growing-market', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/video-formulating-frozen-desserts-allulose', 'Dairy, Dairy / Dessert, Dairy / Dessert / Other desserts (Including frozen)'],
    ['/na/en-us/solving-a-challenge/resource-library/video-functional-build-back', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-high-protein-beverage', 'Non-alcoholic beverage, Non-alcoholic beverage / Sport drink'],
    ['/na/en-us/solving-a-challenge/resource-library/video-how-to-register-on-myingredion', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-ideas-to-solutions', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-insights-reduced-sugar-dairy-podcast', 'Dairy'],
    ['/na/en-us/solving-a-challenge/resource-library/video-lets-talk-texture', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-lowfodmap-digestive-health', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-meat-cost-savings', 'Meat, fish, poultry'],
    ['/na/en-us/solving-a-challenge/resource-library/video-myingredion-customer-portal', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-nutritional-bev', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-order-products-how-to-myingredion', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-organic-promises-webinar', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-plant-based-high-protein-yogurt', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-plant-based-meat-alternative-nugget', 'Meat alternative Batter & breading'],
    ['/na/en-us/solving-a-challenge/resource-library/video-plant-based-seafood-patty', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/video-proteins-of-the-future', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-reduced-sugar-chile-lime-sauce', 'Savory, Savory / Sauces & dressing'],
    ['/na/en-us/solving-a-challenge/resource-library/video-reduced-sugar-choco-protein-bev', 'Non-alcoholic beverage, Non-alcoholic beverage / Functional Beverage'],
    ['/na/en-us/solving-a-challenge/resource-library/video-reduced-sugar-electolyte-beverage', 'Non-alcoholic beverage, Non-alcoholic beverage / Sport drink'],
    ['/na/en-us/solving-a-challenge/resource-library/video-reduced-sugar-ice-cream', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-regenerative-agriculture', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-respond-to-changing-consumer-behaviors', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-salad-dressing-cost-savings', 'Savory / Sauces & dressing'],
    ['/na/en-us/solving-a-challenge/resource-library/video-south-sioux-city-panel', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-south-sioux-city-sustainability', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-south-sioux-city-sustainability_msm_moved', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-speed-up-innovation-in-plant-based-meat', 'Meat alternative'],
    ['/na/en-us/solving-a-challenge/resource-library/video-sugar-reduction-challenge-solving-webinar', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-sweet-and-savory-korean-barbeque-sauce', 'Savory, Savory / Sauces & dressing'],
    ['/na/en-us/solving-a-challenge/resource-library/video-texture-gluten-free-pizza', 'Bakery'],
    ['/na/en-us/solving-a-challenge/resource-library/video-thin-crispy-gluten-free-pizza', 'Bakery'],
    ['/na/en-us/solving-a-challenge/resource-library/video-track-order-myingredion', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-traditional-style-gluten-free-pizza', 'Bakery'],
    ['/na/en-us/solving-a-challenge/resource-library/video-vegan-frozen-dessert', 'Dairy alternative (Dairy free) / Frozen dessert'],
    ['/na/en-us/solving-a-challenge/resource-library/video-what-is-lowfodmap', ''],
    ['/na/en-us/solving-a-challenge/resource-library/video-yogurt-cost-savings', 'Dairy / Yogurt'],
    ['/na/en-us/solving-a-challenge/resource-library/webinar-reducing-sugar-without-losing-taste', ''],
    ['/na/en-us/solving-a-challenge/resource-library/webinar-the-benefits-and-solutions-of-fiber', ''],
    ['/na/en-us/solving-a-challenge/resource-library/wild-berry-flavored-beverage', 'Non-alcoholic beverage / Other beverages, Beverage emulsion & powder / Beverage emulsion, Non-alcoholic beverage, Beverage emulsion & powder'],
    ['/na/en-us/solving-a-challenge/resource-library/yogurt-texture-whitepaper', 'Dairy, Dairy / Yogurt']
]);

