# automatically update <branch> in PR description with the branch name
name: Update PR Description

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR description
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const branchName = pr.head.ref;
            const prBody = pr.body || ''; // Default to empty string if null
            const updatedBody = prBody.replace('<branch>', branchName);

            if (prBody !== updatedBody) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: updatedBody,
              });
            } else {
              console.log('No changes needed.');
            }
